name: 'Dazed & Confused Quotes'
favicon: null
layout_spectrum: 0.1045
typography_spectrum: 0.92041
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b9d8c6'
    - '#fe825c'
    - '#2a4f48'
    - '#89958b'
    - '#84311b'
  brandStrength: 0.125
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.15777890989556909
purpose: []
