name: 'Dazed & Confused Quotes'
favicon: null
layout_spectrum: 0.76335
typography_spectrum: 0.2166032143868506
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#136ffb'
    - '#2c97fc'
    - '#7bfdfe'
    - '#50d1fd'
    - '#59a7fb'
  brandStrength: 0.9380215967539698
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.15777890989556909
purpose: []
