name: 'Dazed & Confused Quotes'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.92041
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebe8e1'
    - '#7d6b5d'
    - '#87cde6'
    - '#a89b92'
    - '#474038'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
